spring:
  application:
    name: lv2-final-mission
  datasource:
    url: jdbc:mysql://${{secrets.DB_URL}}:3306/oneonone
    username: ${{secrets.DB_USER}}
    password: ${{secrets.DB_PASSWORD}}
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true